### ISSUE TITLE
For AWS hub enable S3 access for workers

### ISSUE THREAD

**Issue by arokem** [learning-2-learn/jhub-deployment#59]
Set workers to have S3 full access on our allocation

**Comment by consideRatio** [comment]
I'll get this done today!

**Comment by consideRatio** [comment]
Done!

All user pods and dask-worker pods now startup with a k8s ServiceAccount specified as configured in the Helm chart. The k8s ServiceAccount is coupled to a AWS IAM Role, which has S3FullAccess permissions - this is defined and can be updated in the infra/eksctl-cluster-config.yaml file if needed.

To trial this out, you can run `aws s3 ls` in a user pod and `env | grep AWS` to inspect the automatically set environment variables.

I had to read up a bit to figure out the most sensible way to get this done.
- I opted to not grant the nodes themselves access, but the pods. This way, malicious software on other pods can't risk doing something bad.
- I looked and found a way to make future adjustment of permissions easier to be flexible with. Two good outcomes came of this in my mind.
  1. The creation of k8s ServiceAccounts with associated AWS IAM Role's having permissions is easy through eksctl and the configuration file in the repo.
  2. The possibility to give a subset of users certain permissions have been enabled because we could in theory just adjust the serviceAccountName of the user pod based on the user, like we in the past have configured other aspects of the user pods based on the user. I guess if we would need to give more fine grained control of the dask-gateway workers associated with a user it becomes a bit more tricky, but probably still possible with some tricks.

**Comment by arokem** [comment]
Wonderful. Thanks for setting this up!
